Replace Express with Fastify #88
bludnic/opentrader pull request #90
Opened 2024-12-30 02:20 UTC by montymi

# Replace Express with Fastify · Issue #88

## About

Converting the library used in `packages/daemon` from [Express.js](https://expressjs.com/) to [Fastify](https://fastify.dev/).
All files edited fall under the `daemon` folder except for `package.json` which needed to be updated to reflect the change in dependencies. 

## Tasks

- [X] Ensure `server.ts` exposed the same functionality to `index.ts` after the library switch
- [X] Additional logging information upon daemon creation
- [X] Ensure proper async/await handling
- [ ] Create tests to verify server usage
- [ ] Validate server creation through the [OpenTrader UI](http://localhost:8000)

## Notes

The RPC server listens on port 8000, with OpenTrader also running on localhost at the same port. In `Contributing.md`, the CLI is said to be found at [port 8000](http://localhost:8000). 

*Am I incorrectly setting the port number when starting up the daemon?*

After creating `dev.db`, a strange environment variable error occurred upon initialization of the project.  The .env file did not load automatically, requiring this command to be manually run in each terminal instance:
```bash
export DATABASE_URL="file:../../../dev.db"
```

2024-12-30 12:11 UTC, bludnic commented
First of all, thank you for your interest in the project. Your contribution is greatly appreciated, and the PR description is very comprehensive.

Answering your questions:

> Am I incorrectly setting the port number when starting up the daemon?

Yes, you did it right.

> After creating dev.db, a strange environment variable error occurred upon initialization of the project. The .env file did not load automatically, requiring this command to be manually run in each terminal instance:

Could you provide more details so I can investigate it? Specifically, what OS are you using, and which command caused the issue (`./bin/cli.sh up` or `moon run prisma:migrate`)? Any logs would be very helpful.

For faster communication, feel free to join our community on Discord: https://discord.gg/RS7y3ffvvG

2024-12-30 12:11 UTC, bludnic requested changes

2024-12-30 12:11 UTC, bludnic commented on package.json
>    }
These dependencies belong to the `@opentrader/daemon` package, so they must be removed from here.

2024-12-30 12:11 UTC, bludnic commented on packages/daemon/package.json
>      "cors": "^2.8.5",
Remove Express related deps: `cors` and `@types/cors`, since you replaced it with `@fastify/cors`.

2024-12-30 12:11 UTC, bludnic commented on packages/daemon/src/server.ts
> +  }
```suggestion
fastify.register(fastifyCors, {
  origin: true,
});

fastify.register(fastifyStatic, {
  root: staticDir,
  prefix: '/', // optional: default '/'
});
```

Let's keep it simple. No need for `try/catch` here. We can catch the error at a higher level.

2024-12-30 12:11 UTC, bludnic commented on packages/daemon/src/server.ts
> +};
Missing new line at the end of the file

2024-12-30 12:11 UTC, bludnic commented on packages/daemon/package.json
> +    "fastify": "^4.0.0",
An error occurs when starting the app, due version incompatibility (`@fastify/cors` requires Fastify version `5.x`)

**Reproduction:**

1. Build the app  `moon run :build`
2. Start the app `./bin/cli.sh up`

**Expected:**

No errors

**Actual**:

Failed to start Fastify server with an error:

```
{"level":50,"time":1735559079752,"pid":4767,"hostname":"penguin","err":{"type":"FastifyError","message":"fastify-plugin: @fastify/cors - expected '5.x' fastify version, '4.29.0' is installed","stack":"FastifyError: fastify-plugin: @fastify/cors - expected '5.x' fastify version, '4.29.0' is installed\n    at Object.checkVersion (file:///home/user/Dev/montymi-opentrader/apps/cli/dist/chunk-WZW7MPLI.mjs:30983:15)\n    at Object.registerPlugin (file:///home/user/Dev/montymi-opentrader/apps/cli/dist/chunk-WZW7MPLI.mjs:31002:20)\n    at Boot.override (file:///home/user/Dev/montymi-opentrader/apps/cli/dist/chunk-WZW7MPLI.mjs:35832:61)\n    at Boot._loadPlugin (file:///home/user/Dev/montymi-opentrader/apps/cli/dist/chunk-WZW7MPLI.mjs:10434:29)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","code":"FST_ERR_PLUGIN_VERSION_MISMATCH","name":"FastifyError","statusCode":500},"msg":"fastify-plugin: @fastify/cors - expected '5.x' fastify version, '4.29.0' is installed"}
```

2024-12-31 23:52 UTC, montymi commented
> > After creating dev.db, a strange environment variable error occurred upon initialization of the project. The .env file did not load automatically, requiring this command to be manually run in each terminal instance:
> 
> Could you provide more details so I can investigate it? Specifically, what OS are you using, and which command caused the issue (`./bin/cli.sh up` or `moon run prisma:migrate`)? Any logs would be very helpful.

I was following the installation guide provided in the README for a desktop running Windows 11. The env issue arose at `moon run prisma:migrate` and was fixed by simply importing the var as described above. 

The error was as follows:
```
Error: task_runner:: run_failed

    x Task prisma:migrate failed to run.
        Process prisma failed: exit code 1

Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DATABASE_URL
    -->    src\schema.prisma:27
    
        |
   26 | provider = "sqlite" 
   27 | url           = env("DATABASE_URL")
        |
        
  Validation Error Count: 1
  [Context: getConfig]
  
  Prisma CLI Version : 6.0.1
```

2024-12-31 23:54 UTC, montymi commented
Hello! I’ve joined the Discord and made the requested changes. Thank you for creating such a great project and making the contribution process so clear. Wishing you a fantastic New Year!

2025-01-05 01:55 UTC, bludnic approved these changes

2025-01-05 01:55 UTC, merged